//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.16 at 02:53:56 PM MESZ 
//


package unidue.ub.sushiclient.service;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * This is the actual response expected from a COUNTER_SUSHI service. A combination of the SUSHI ReportResponse with the COUNTER "Report" added. NOTE: The ReportRequest and ReportResponse are defined in the SUSHI1_6.xsd and the COUNTER report is defined in the Counter4_0.xsd.
 * 
 * <p>Java class for CounterReportResponse complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CounterReportResponse">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.niso.org/schemas/sushi}ReportResponse">
 *       &lt;sequence>
 *         &lt;element name="Report" type="{http://www.niso.org/schemas/counter}Reports"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CounterReportResponse", namespace = "http://www.niso.org/schemas/sushi/counter", propOrder = {
    "report"
})
@XmlRootElement
public class CounterReportResponse
    extends ReportResponse
{

    @XmlElement(name = "Report", required = true, nillable = true)
    protected Report report;

    /**
     * Gets the value of the report property.
     * 
     * @return
     *     possible object is
     *     {@link Reports }
     *     
     */
    public Report getReport() {
        return report;
    }

    /**
     * Sets the value of the report property.
     * 
     * @param value
     *     allowed object is
     *     {@link Reports }
     *     
     */
    public void setReport(Report value) {
        this.report = value;
    }

}
