//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.16 at 02:53:56 PM MESZ 
//


package unidue.ub.sushiclient.service;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ExceptionSeverity.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ExceptionSeverity">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Info"/>
 *     &lt;enumeration value="Debug"/>
 *     &lt;enumeration value="Warning"/>
 *     &lt;enumeration value="Error"/>
 *     &lt;enumeration value="Fatal"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "ExceptionSeverity", namespace = "http://www.niso.org/schemas/sushi")
@XmlEnum
public enum ExceptionSeverity {


    /**
     * Info – type of severity that provides more information about the response. Can be included in a chain of other severity levels.
     * 
     */
    @XmlEnumValue("Info")
    INFO("Info"),

    /**
     * Debug – type of severity that provides debugging information about the response. Can be included in a chain of other severity levels.
     * 
     */
    @XmlEnumValue("Debug")
    DEBUG("Debug"),

    /**
     * Warning – type of severity that does not interrupt the completion of the transaction (defined as: request->data->response) but gives more information about the response. It could be followed by more exceptions (Info, Debug).
     * 
     */
    @XmlEnumValue("Warning")
    WARNING("Warning"),

    /**
     * Error – type of severity that would return no payload. It could be followed by more exceptions (Info, Debug).
     * 
     */
    @XmlEnumValue("Error")
    ERROR("Error"),

    /**
     * Fatal – type of severity that would return no payload. It could be followed by more exceptions (Info, Debug).
     * 
     */
    @XmlEnumValue("Fatal")
    FATAL("Fatal");
    private final String value;

    ExceptionSeverity(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ExceptionSeverity fromValue(String v) {
        for (ExceptionSeverity c: ExceptionSeverity.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
