//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.16 at 02:53:56 PM MESZ 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.niso.org/schemas/counter", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package unidue.ub.sushiclient.service;
